# Generated by Django 5.2.6 on 2025-11-07 16:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Labeling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('final_date', models.DateField(blank=True, null=True)),
                ('items_per_user', models.PositiveIntegerField(blank=True, null=True)),
                ('column_names', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Ativa'), ('archived', 'Arquivada'), ('finished', 'Finalizada')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rotulations_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotulations', to='project.project')),
            ],
            options={
                'ordering': ['-created_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LabelingSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('labeling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='labeling.labeling')),
            ],
            options={
                'ordering': ['labeling_id', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LabelingElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('text', models.CharField(max_length=500)),
                ('required', models.BooleanField(default=False)),
                ('question_type', models.CharField(choices=[('text', 'Texto'), ('bool', 'Booleano'), ('number', 'Numérico'), ('multiple_choice', 'Múltipla escolha'), ('range', 'Faixa'), ('context', 'Contexto')], max_length=32)),
                ('column_name', models.CharField(blank=True, max_length=200)),
                ('labeling_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='labeling.labelingsection')),
            ],
            options={
                'ordering': ['labeling_section_id', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MultipleChoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('value', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=1)),
                ('labeling_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='labeling.labelingelement')),
            ],
            options={
                'ordering': ['labeling_element_id', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.FloatField()),
                ('end', models.FloatField()),
                ('step', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(1e-07)])),
                ('labeling_element', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='range_cfg', to='labeling.labelingelement')),
            ],
        ),
        migrations.CreateModel(
            name='LabelingMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_done', models.PositiveIntegerField(default=0)),
                ('role', models.CharField(choices=[('owner', 'Dono'), ('admin', 'Administrador'), ('annotator', 'Rotulador'), ('viewer', 'Leitor')], default='annotator', max_length=16)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('labeling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='labeling.labeling')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labeling_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-joined_at'],
                'unique_together': {('user', 'labeling')},
            },
        ),
        migrations.AddConstraint(
            model_name='labelingsection',
            constraint=models.UniqueConstraint(fields=('labeling', 'order'), name='unique_section_order_per_labeling'),
        ),
        migrations.AddConstraint(
            model_name='labelingelement',
            constraint=models.UniqueConstraint(fields=('labeling_section', 'order'), name='unique_element_order_per_section'),
        ),
        migrations.AddConstraint(
            model_name='multiplechoiceitem',
            constraint=models.UniqueConstraint(fields=('labeling_element', 'order'), name='unique_choice_order_per_element'),
        ),
        migrations.AddConstraint(
            model_name='questionrange',
            constraint=models.CheckConstraint(condition=models.Q(('end__gt', models.F('start'))), name='range_end_gt_start'),
        ),
    ]
