# Generated by Django 5.2.6 on 2025-11-19 15:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0002_alter_labeling_created_by_alter_labeling_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labeling',
            name='final_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='labeling',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2025, 11, 19, 15, 8, 2, 629478, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='multiplechoiceitem',
            name='labeling_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiple_choice_items', to='labeling.labelingelement'),
        ),
        migrations.AlterField(
            model_name='questionrange',
            name='labeling_element',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='question_range', to='labeling.labelingelement'),
        ),
    ]
