# Generated by Django 5.2.6 on 2025-11-19 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0003_alter_labeling_final_date_alter_labeling_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labeling',
            name='start_date',
            field=models.DateField(default=datetime.date(2025, 11, 19)),
        ),
    ]
