# Generated by Django 5.2.6 on 2025-11-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0004_alter_labeling_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelingelement',
            name='context_type',
            field=models.CharField(blank=True, choices=[('text', 'Texto'), ('number', 'Número'), ('date', 'Data'), ('category', 'categoria')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='labelingelement',
            name='text',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
