# Generated by Django 5.2.6 on 2025-11-24 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0005_labelingelement_context_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labeling',
            old_name='items_per_user',
            new_name='users_per_item',
        ),
        migrations.AlterField(
            model_name='labeling',
            name='start_date',
            field=models.DateField(default=datetime.date(2025, 11, 24)),
        ),
    ]
