# Generated by Django 5.2.6 on 2025-11-24 18:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0006_rename_items_per_user_labeling_users_per_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labeling',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
