# Generated by Django 5.2.6 on 2025-11-26 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0007_alter_labeling_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labeling',
            name='users_per_item',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
