# Generated by Django 5.2.6 on 2025-11-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0008_alter_labeling_users_per_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelingelement',
            name='allow_multiple',
            field=models.BooleanField(default=False),
        ),
    ]
