# Generated by Django 5.2.6 on 2025-11-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0009_labelingelement_allow_multiple'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelingelement',
            name='question_type',
            field=models.CharField(choices=[('text', 'Texto'), ('number', 'Numérico'), ('multiple_choice', 'Múltipla escolha'), ('range', 'Faixa'), ('context', 'Contexto')], max_length=32),
        ),
    ]
