# Generated by Django 5.2.6 on 2025-12-08 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0011_labeling_block_section_back'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labeling',
            options={'ordering': ['created_at', 'title']},
        ),
    ]
