# Generated by Django 5.2.6 on 2025-12-08 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0012_alter_labeling_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labeling',
            options={'ordering': ['-created_at', 'title']},
        ),
    ]
