# Generated by Django 5.2.6 on 2025-12-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0013_alter_labeling_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='labeling',
            name='guide',
            field=models.TextField(blank=True, default=''),
        ),
    ]
