# Generated by Django 5.2.6 on 2025-12-11 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0014_labeling_guide'),
        ('user', '0005_usergroup_groupmembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelingGroupQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_answers_per_item', models.PositiveSmallIntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.usergroup')),
                ('labeling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_quotas', to='labeling.labeling')),
            ],
            options={
                'unique_together': {('labeling', 'group')},
            },
        ),
    ]
