# Generated by Django 5.2.6 on 2026-01-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0016_labeling_decision'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelingelement',
            name='decisive_question',
            field=models.BooleanField(default=False),
        ),
    ]
