# Generated by Django 5.2.6 on 2026-01-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0017_labelingelement_decisive_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelingelement',
            name='context_type',
            field=models.CharField(blank=True, choices=[('text', 'Texto'), ('number', 'Número'), ('date', 'Data'), ('category', 'categoria'), ('code', 'Código')], max_length=32, null=True),
        ),
    ]
