# Generated by Django 5.2.6 on 2026-01-08 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0018_alter_labelingelement_context_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labelingelement',
            name='decisive_question',
        ),
        migrations.AddField(
            model_name='labeling',
            name='decisive_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='labeling.labelingelement'),
        ),
    ]
