# Generated by Django 5.2.6 on 2026-01-08 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0019_remove_labelingelement_decisive_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labeling',
            name='decisive_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='labeling.labelingelement'),
        ),
    ]
