# Generated by Django 5.2.6 on 2026-02-03 12:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0021_alter_labelingelement_context_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='labelingmembership',
            index=models.Index(fields=['user', 'labeling'], name='user_labeling_idx'),
        ),
    ]
