# Generated by Django 5.2.11 on 2026-02-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0022_labelingmembership_user_labeling_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labelingsection',
            options={'ordering': ['labeling_id', 'form_type', 'order']},
        ),
        migrations.RemoveConstraint(
            model_name='labelingsection',
            name='unique_section_order_per_labeling',
        ),
        migrations.AddField(
            model_name='labeling',
            name='has_background_form',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labelingsection',
            name='form_type',
            field=models.CharField(choices=[('main', 'Principal'), ('background', 'Background')], db_index=True, default='main', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='labelingsection',
            constraint=models.UniqueConstraint(fields=('labeling', 'form_type', 'order'), name='unique_section_order_per_labeling_form_type'),
        ),
    ]
