# Generated by Django 5.2.6 on 2026-02-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0023_alter_labelingsection_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labeling',
            name='distribution_strategy',
            field=models.CharField(choices=[('auto', 'Automática'), ('specified', 'Estipulada'), ('per_person', 'Por pessoa')], default='auto', max_length=32),
        ),
    ]
