# Generated by Django 5.2.6 on 2026-03-02 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0024_labeling_distribution_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplechoiceitem',
            name='optional_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multiple_choice_item_sections', to='labeling.labelingsection'),
        ),
    ]
