# Generated by Django 5.2.6 on 2026-03-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0024_labeling_distribution_strategy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelingelement',
            name='context_type',
            field=models.CharField(blank=True, choices=[('text', 'Texto'), ('number', 'Número'), ('image', 'Imagem'), ('date', 'Data'), ('category', 'categoria'), ('code', 'Código'), ('audio', 'Áudio')], max_length=32, null=True),
        ),
    ]
