# Generated by Django 5.2.6 on 2026-03-03 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0026_alter_labeling_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelingsection',
            name='multiple_choice_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='labeling.multiplechoiceitem'),
        ),
        migrations.AlterField(
            model_name='labelingsection',
            name='form_type',
            field=models.CharField(choices=[('main', 'Principal'), ('background', 'Background'), ('multiple_choice', 'Múltipla escolha')], db_index=True, default='main', max_length=16),
        ),
        migrations.AlterField(
            model_name='labelingsection',
            name='labeling',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='labeling.labeling'),
        ),
    ]
