# Generated by Django 6.0.3 on 2026-03-19 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0029_merge_context_type_branches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labelingsection',
            name='multiple_choice_item',
        ),
        migrations.RemoveField(
            model_name='multiplechoiceitem',
            name='optional_section',
        ),
        migrations.AddField(
            model_name='multiplechoiceitem',
            name='follow_up_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_for', to='labeling.labelingelement'),
        ),
        migrations.AlterField(
            model_name='labelingsection',
            name='form_type',
            field=models.CharField(choices=[('main', 'Principal'), ('background', 'Background')], db_index=True, default='main', max_length=16),
        ),
        migrations.AlterField(
            model_name='labelingsection',
            name='labeling',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='labeling.labeling'),
        ),
    ]
