# Generated by Django 6.0.3 on 2026-04-07 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0027_questionrange_labels'),
        ('labeling', '0030_remove_labelingsection_multiple_choice_item_and_more'),
    ]

    operations = [
    ]
