# Generated by Django 6.0.3 on 2026-05-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0032_labeling_decision_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='labeling',
            name='form_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='labeling',
            name='distribution_strategy',
            field=models.CharField(choices=[('auto', 'Automática'), ('specified', 'Estipulada'), ('per_person', 'Por pessoa'), ('anonymous_mode', 'Modo anônimo')], default='auto', max_length=32),
        ),
        migrations.AlterField(
            model_name='labeling',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Ativa'), ('archived', 'Arquivada'), ('finished', 'Finalizada')], default='draft'),
        ),
    ]
