# Generated by Django 5.2.11 on 2026-06-06 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0034_labeling_anonymous_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelingelement',
            name='question_type',
            field=models.CharField(choices=[('text', 'Texto'), ('number', 'Numérico'), ('multiple_choice', 'Múltipla escolha'), ('range', 'Faixa'), ('email', 'Email'), ('context', 'Contexto')], max_length=32),
        ),
    ]
