# Generated by Django 6.0.3 on 2026-06-08 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0034_labeling_anonymous_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='labeling',
            name='items_per_group',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.DeleteModel(
            name='LabelingGroupQuota',
        ),
    ]
