# Generated by Django 6.0.3 on 2026-06-10 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0035_alter_labelingelement_question_type'),
        ('labeling', '0035_labeling_items_per_group_delete_labelinggroupquota'),
    ]

    operations = [
    ]
