# Generated by Django 6.0.3 on 2026-07-27 17:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0036_merge_20260610_1920'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='labelingmembership',
            name='last_opened_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddIndex(
            model_name='labelingmembership',
            index=models.Index(fields=['user', 'last_opened_at'], name='user_last_opened_idx'),
        ),
    ]
