# Generated by Django 6.0.3 on 2026-08-08 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0037_labelingmembership_last_opened_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelingAIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('gemini', 'Gemini')], max_length=16)),
                ('encrypted_api_key', models.TextField()),
                ('key_hint', models.CharField(blank=True, default='', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('labeling', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_config', to='labeling.labeling')),
            ],
        ),
    ]
