# Generated by Django 6.0.3 on 2026-08-25 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0038_transfer_project_perms_to_labeling'),
        ('project', '0006_alter_projectmembership_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labeling',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labelings', to='project.project'),
        ),
        migrations.AlterField(
            model_name='labelingmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Dono'), ('admin', 'Administrador'), ('viewer', 'Leitor'), ('annotator', 'Rotulador')], default='annotator', max_length=16),
        ),
    ]
