import type { Metadata } from "next";
import "./globals.css";
import AuthGuard from "@/components/auth-guard";
import { SidebarProvider } from "@/components/side-bar/sidebar_provider";
import { Montserrat } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Annotaise",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} antialiased`}
        style={{ fontFamily: "var(--font-montserrat)" }}
      >
        <SidebarProvider>
          <AuthGuard>
            {children}
            <Toaster />
          </AuthGuard>
        </SidebarProvider>
      </body>
    </html>
  );
}
