name: annotaise

services:

  api:
    build: ./backend/
    volumes:
      - ./backend/:/src
      - ./backend/static:/static
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DJANGO_DB_HOST: db
      DJANGO_DB_PORT: 5432
      DJANGO_DB_NAME: ${DJANGO_DB_NAME}
      DJANGO_DB_USER: ${DJANGO_DB_USER}
      DJANGO_DB_PASS: ${DJANGO_DB_PASS}
      DJANGO_SUPERUSER_USER: ${DJANGO_SUPERUSER_USER}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
      DEFAULT_FROM_EMAIL: ${DEFAULT_FROM_EMAIL}
      FRONTEND_URL: ${FRONTEND_URL}

  frontend:
    build:
      context: ./frontend
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${DJANGO_DB_NAME}
      POSTGRES_USER: ${DJANGO_DB_USER}
      POSTGRES_PASSWORD: ${DJANGO_DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - pg_annotaise:/var/lib/postgresql/data

volumes:
  pg_annotaise:
    driver: local
