# Generated by Django 5.2.6 on 2025-11-03 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0001_initial'),
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answered_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='answers_given', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='item.item')),
                ('labeling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='project.labeling')),
                ('labeling_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='project.labelingelement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
