# Generated by Django 5.2.6 on 2025-11-24 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='labeling_question',
        ),
    ]
