# Generated by Django 5.2.6 on 2026-02-03 12:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0002_remove_answer_labeling_question'),
        ('item', '0003_item_decision_payload'),
        ('labeling', '0022_labelingmembership_user_labeling_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['answered_by', 'item'], name='answer_user_item_idx'),
        ),
    ]
