# Generated by Django 5.2.11 on 2026-02-10 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0003_answer_answer_user_item_idx'),
        ('labeling', '0023_alter_labelingsection_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answered_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='background_answers_given', to=settings.AUTH_USER_MODEL)),
                ('labeling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='background_answers', to='labeling.labeling')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['labeling', 'answered_by'], name='bg_answer_lbl_user_idx')],
                'constraints': [models.UniqueConstraint(fields=('labeling', 'answered_by'), name='unique_background_answer_per_user')],
            },
        ),
    ]
