# Generated by Django 5.2.6 on 2026-03-03 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0004_backgroundanswer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='backgroundanswer',
            name='answered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='background_answers_given', to=settings.AUTH_USER_MODEL),
        ),
    ]
