# Generated by Django 6.0.3 on 2026-06-08 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0005_alter_answer_answered_by_and_more'),
        ('user', '0009_usergroupmembership_unique_membership_between_user_and_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='responded_as',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers_filling_quota', to='user.usergroup'),
        ),
    ]
