# Generated by Django 5.2.6 on 2025-11-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_projectmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Proprietário'), ('contributor', 'Colaborador'), ('viewer', 'Visualizador')], default='viewer', max_length=50),
        ),
    ]
