# Generated by Django 5.2.6 on 2026-02-03 12:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_projectmembership_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='projectmembership',
            index=models.Index(fields=['project', 'user'], name='membership_project_user_idx'),
        ),
    ]
