# Generated by Django 6.0.3 on 2026-08-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_project_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Proprietário'), ('contributor', 'Colaborador'), ('viewer', 'Visualizador'), ('annotator', 'Anotador')], default='viewer', max_length=50),
        ),
    ]
