# Generated by Django 5.2.6 on 2025-11-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(blank=True, choices=[('standard', 'Padrao'), ('editor', 'Editor'), ('admin', 'Administrador')], default='standard', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
