# Generated by Django 5.2.6 on 2025-12-09 14:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_invitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='id',
        ),
        migrations.AlterField(
            model_name='invitation',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
