# Generated by Django 6.0.3 on 2026-06-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_customuser_onboarding_status_invitation_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupMembership',
            new_name='UserGroupMembership',
        ),
        migrations.AddField(
            model_name='usergroup',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
