# Generated by Django 6.0.3 on 2026-06-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_rename_groupmembership_usergroupmembership_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
