# Generated by Django 6.0.3 on 2026-06-08 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_usergroup_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='usergroupmembership',
            constraint=models.UniqueConstraint(fields=('group', 'user'), name='unique_membership_between_user_and_group'),
        ),
    ]
