# Generated by Django 6.0.3 on 2026-09-22 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_usergroupmembership_unique_membership_between_user_and_group'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
