# Generated by Django 5.2.6 on 2025-11-07 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labeling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField()),
                ('row_index', models.PositiveIntegerField()),
                ('status', models.CharField(default='pending', max_length=50)),
                ('labeling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='labeling.labeling')),
            ],
        ),
    ]
