# Generated by Django 5.2.6 on 2026-01-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_item_assigned_to_item_assignment_date_itemmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='decision_payload',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
