# Generated by Django 6.0.3 on 2026-06-09 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_item_llm_tiebreak_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmembership',
            name='last_seen_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
